# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
    ]
