# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_auto_20160712_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='date_time',
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='stop_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
