# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0007_auto_20160712_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='private_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
