# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_person_private_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='time',
            name='stop_time',
            field=models.DateTimeField(null=True),
        ),
    ]
