# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0009_auto_20160712_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='stop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
