# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0010_auto_20160712_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='current_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.Time'),
        ),
        migrations.AlterField(
            model_name='time',
            name='stop_time',
            field=models.DateTimeField(null=True),
        ),
    ]
