# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0012_auto_20160716_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='group',
        ),
    ]
