# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0013_auto_20160716_1208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='group',
            new_name='team',
        ),
    ]
