# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0014_auto_20160716_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='current_snippet',
        ),
        migrations.AddField(
            model_name='person',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timesheet.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='time',
            name='stop_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
