# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0017_auto_20160730_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
